pmic_basin_cove: Fix the build error
The commit fd50cc3aefbe1c02aec3a2b9ed866b61771c0852 has moved away the
ipc definitions from the original upstream commit
fd50cc3aefbe1c02aec3a2b9ed866b61771c0852. This has caused below build
error for this driver. Fix it

  CC      drivers/regulator/pmic_basin_cove.o
drivers/regulator/pmic_basin_cove.c: In function 'intel_pmic_reg_is_enabled':
drivers/regulator/pmic_basin_cove.c:52:2: error: implicit declaration of function 'intel_scu_ipc_ioread8'
drivers/regulator/pmic_basin_cove.c: In function 'intel_pmic_reg_enable':
drivers/regulator/pmic_basin_cove.c:79:2: error: implicit declaration of function 'intel_scu_ipc_iowrite8'

Reported-by: Ziyu Jiang <ziyux.jiang@intel.com>
Signed-off-by: Srinidhi Kasagar <srinidhi.kasagar@intel.com>